apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-wp
  template:
    metadata:
      labels:
        app: my-wp
    spec:
      containers:
      - name: my-app
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/nach-wp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: wordpress-env-secret
      imagePullSecrets:
      - name: regcred
