apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-wp
  template:
    metadata:
      labels:
        app: my-wp
    spec:
      containers:
      - name: my-app
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/nach-wp:latest
        imagePullPolicy: Always # Enforces image pull to avoid using old local images
        ports:
        - containerPort: 80
        env:
        - secretRef: 
            name: wordpress-env-secret
      imagePullSecrets:
      - name: regcred # Name of the secret created in Step 2

