apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: wp-external-secret-ssm # The resulting K8s Secret
    creationPolicy: Owner
  data:
    - secretKey: WORDPRESS_DB_HOST # Key inside the K8s Secret
      remoteRef:
        key: /nach/wp/db_host # AWS SSM Parameter Name
    - secretKey: WORDPRESS_DB_USER
      remoteRef:
        key: /nach/wp/db_user
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: /nach/wp/db_password
    - secretKey: WORDPRESS_DB_NAME
      remoteRef:
        key: /nach/wp/db_name