apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata: 
  name: ingress-rule-test
spec:
  ingressClassName: ingress-class
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wp-svc
            port:
              number: 80
