apiVersion: v1
kind: Secret
metadata:
  name: wordpress-env-secret
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "mariadb-svc"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_PASSWORD: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"