apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: mariadb-external-secret-ssm # The resulting K8s Secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD # Key inside the K8s Secret
      remoteRef:
        key: /nach/db/root_password # AWS SSM Parameter Name
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: /nach/db/database
    - secretKey: MYSQL_USER
      remoteRef:
        key: /nach/db/user
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: /nach/db/password