apiVersion: v1
kind: Secret
metadata:
  name: mysql-env-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "somewordpress"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "wordpress"