apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-crb

roleRef:
  kind: ClusterRole
  name: ingress-cluster-role 
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ingress-sa
    namespace: ingress-nginx
